'use strict';
const CLASSES=['الأول الإعدادي','الثاني الإعدادي','الثالث الإعدادي','الأول الثانوي','الثاني الثانوي','الثالث الثانوي'];
const KEY='miyaar-attendance-v1',blank=()=>({students:[],codes:[],attendance:{},nextCode:1});
let db;try{db={...blank(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{db=blank()}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(db))}catch{toast('مساحة التخزين ممتلئة؛ احذف بعض الأكواد لتوفير مساحة.')}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const prettyDate=s=>new Date(s+'T12:00:00').toLocaleDateString('ar-EG',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2800)};
function init(){ $('#today').textContent=prettyDate(dayKey());$('#attendance-date').value=dayKey();$('#student-class').innerHTML=CLASSES.map((c,i)=>`<option value="${i}">${c}</option>`).join('');$('#student-class-filter').innerHTML='<option value="">كل الصفوف</option>'+CLASSES.map((c,i)=>`<option value="${i}">${c}</option>`).join('');const reprint=document.createElement('button');reprint.id='reprint-codes';reprint.className='secondary print-btn';reprint.textContent='إعادة طباعة الأكواد المحفوظة';reprint.disabled=!db.codes.length;$('#print-codes').after(reprint);reprint.onclick=()=>{if(db.codes.length)renderCodes(db.codes);else toast('لا توجد أكواد محفوظة للطباعة بعد.')};render() }
function render(){renderHome();renderStudents();renderAttendance()}
function renderHome(){$('#stat-students').textContent=db.students.length;$('#stat-attendance').textContent=(db.attendance[dayKey()]||[]).length;$('#class-summary').innerHTML=CLASSES.map((c,i)=>{let n=db.students.filter(s=>+s.classId===i).length;return `<div class="class-row"><span>${c}</span><div class="class-meter"><i style="width:${Math.min(100,n*9)}%"></i></div><b>${n}</b></div>`}).join('')}
function renderStudents(){const q=$('#student-search').value.trim().toLowerCase(),cl=$('#student-class-filter').value;const a=db.students.filter(s=>(!cl||String(s.classId)===cl)&&(`${s.name} ${s.phone} ${s.code||''}`.toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name,'ar'));$('#student-count').textContent=`${a.length} طالب`;$('#student-list').innerHTML=`<div class="student-row student-header"><span>اسم الطالب</span><span>الصف</span><span>رقم الهاتف</span><span>الكود والإجراءات</span></div>`+(a.length?a.map(s=>`<div class="student-row"><div class="student-name"><span class="avatar">${esc(s.name.trim()[0]||'؟')}</span>${esc(s.name)}</div><span>${CLASSES[+s.classId]||'—'}</span><span dir="ltr" style="text-align:right">${esc(s.phone||'—')}</span><div class="row-actions"><span class="code-tag">${esc(s.code||'بدون كود')}</span><button data-edit="${s.id}">تعديل</button><button data-delete="${s.id}">حذف</button></div></div>`).join(''):`<div class="empty-state"><span>♙</span><b>${db.students.length?'لا توجد نتائج مطابقة':'لا يوجد طلاب مسجلون بعد'}</b><small>${db.students.length?'جرّب تغيير البحث أو الصف.':'أضف طالبًا جديدًا لبدء تنظيم فصلك.'}</small></div>`);$$('[data-edit]').forEach(b=>b.onclick=()=>editStudent(b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteStudent(b.dataset.delete))}
function renderAttendance(){const date=$('#attendance-date').value,records=(db.attendance[date]||[]).slice().sort((a,b)=>a.time.localeCompare(b.time));$('#today-count').textContent=records.length;$('#attendance-subtitle').textContent=prettyDate(date);$('#attendance-list').innerHTML=records.length?records.map(r=>{const s=db.students.find(x=>x.id===r.studentId);return s?`<div class="attendance-item"><span class="avatar">${esc(s.name.trim()[0]||'؟')}</span><div><strong>${esc(s.name)}</strong><small>${esc(CLASSES[+s.classId]||'')} · ${esc(s.code||'')}</small></div><span class="present">حاضر · ${esc(r.time)}</span></div>`:''}).join(''):`<div class="empty-attendance">لم يُسجّل حضور بعد لهذا اليوم.<br>امسح كود أول طالب للبدء.</div>`}
function go(page){$$('.page').forEach(p=>p.classList.remove('active'));$(`#page-${page}`).classList.add('active');$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#page-title').textContent=({home:'نظرة عامة',students:'الطلاب',attendance:'تسجيل الحضور',codes:'طباعة الأكواد'})[page];if(page==='attendance')renderAttendance()}
$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));$('#student-search').oninput=renderStudents;$('#student-class-filter').onchange=renderStudents;$('#attendance-date').onchange=renderAttendance;
$('#add-student-btn').onclick=()=>openStudent();$('#cancel-student').onclick=()=>$('#student-dialog').close();
function openStudent(s=null){$('#student-form').reset();$('#student-id').value=s?.id||'';$('#student-name').value=s?.name||'';$('#student-phone').value=s?.phone||'';$('#student-class').value=s?.classId??0;$('#assigned-code').textContent=s?.code||'امسح كودًا لربطه بالطالب';$('#dialog-title').textContent=s?'تعديل بيانات الطالب':'إضافة طالب جديد';$('#link-code-input').value='';$('#link-scanner').hidden=true;$('#student-dialog').showModal()}
function editStudent(id){const s=db.students.find(x=>x.id===id);if(s)openStudent(s)}
function deleteStudent(id){const s=db.students.find(x=>x.id===id);if(!s)return;if(!confirm(`حذف الطالب ${s.name}؟ سيبقى سجل الحضور السابق كما هو.`))return;db.students=db.students.filter(x=>x.id!==id);save();render();toast('تم حذف الطالب')}
function linkCode(code){code=code.trim().toUpperCase();if(!/^MATH-\d{6}$/.test(code)){toast('الكود ده مش من أكواد الموقع.');return false}if(!db.codes.some(c=>c.code===code)){db.codes.push({code,used:true,created:new Date().toISOString()});const number=Number(code.slice(5));if(Number.isFinite(number))db.nextCode=Math.max(db.nextCode,number+1);save()}const owner=db.students.find(s=>s.code===code&&s.id!==$('#student-id').value);if(owner){toast(`الكود مرتبط بالفعل بالطالب ${owner.name}`);return false}$('#assigned-code').textContent=code;$('#link-code-input').value=code;return true}
$('#link-manual-btn').onclick=()=>linkCode($('#link-code-input').value);
$('#student-form').onsubmit=e=>{e.preventDefault();const id=$('#student-id').value,name=$('#student-name').value.trim(),phone=$('#student-phone').value.trim(),classId=$('#student-class').value,code=$('#assigned-code').textContent.startsWith('امسح')?'':$('#assigned-code').textContent,old=db.students.find(s=>s.id===id);if(!name){toast('اكتب اسم الطالب');return}if(old)Object.assign(old,{name,phone,classId,code});else db.students.push({id:crypto.randomUUID?.()||String(Date.now()),name,phone,classId,code});save();$('#student-dialog').close();render();toast(old?'تم تحديث بيانات الطالب':'تم تسجيل الطالب')};
function recordAttendance(value){const code=value.trim().toUpperCase();if(!code)return;const student=db.students.find(s=>s.code===code);if(!student){toast('هذا الكود غير مرتبط بطالب. اربطه من صفحة الطلاب أولًا.');return}const date=$('#attendance-date').value;if(!db.attendance[date])db.attendance[date]=[];if(db.attendance[date].some(x=>x.studentId===student.id)){toast(`تم تسجيل حضور ${student.name} بالفعل اليوم.`);return}db.attendance[date].push({studentId:student.id,code,time:new Date().toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})});save();render();toast(`تم تسجيل حضور ${student.name} ✓`)}
$('#manual-scan').onsubmit=e=>{e.preventDefault();recordAttendance($('#manual-code').value);$('#manual-code').value='';$('#manual-code').focus()};
// Compact QR Code Model 2 encoder, version 1-L: MATH-000001 payload fits in 17 bytes.
const EXP=new Array(512),LOG=new Array(256);{let x=1;for(let i=0;i<255;i++){EXP[i]=x;LOG[x]=i;x<<=1;if(x&256)x^=0x11d}for(let i=255;i<512;i++)EXP[i]=EXP[i-255]}
const mul=(a,b)=>a&&b?EXP[LOG[a]+LOG[b]]:0;
function ecCodewords(data,n){let gen=[1];for(let i=0;i<n;i++){const next=Array(gen.length+1).fill(0);gen.forEach((v,j)=>{next[j]^=v;next[j+1]^=mul(v,EXP[i])});gen=next}const rem=Array(n).fill(0);for(const d of data){const factor=d^rem.shift();rem.push(0);for(let i=0;i<n;i++)rem[i]^=mul(gen[i+1],factor)}return rem}
function makeQR(text){const bytes=[...new TextEncoder().encode(text)];if(bytes.length>17)throw Error('الكود أطول من سعة QR v1-L');let bits=[];const put=(v,n)=>{for(let i=n-1;i>=0;i--)bits.push((v>>>i)&1)};put(4,4);put(bytes.length,8);bytes.forEach(b=>put(b,8));for(let i=0;i<Math.min(4,152-bits.length);i++)bits.push(0);while(bits.length%8)bits.push(0);let data=[];for(let i=0;i<bits.length;i+=8)data.push(bits.slice(i,i+8).reduce((a,b)=>(a<<1)|b,0));for(let p=0;data.length<19;p++)data.push(p%2?0x11:0xec);const all=data.concat(ecCodewords(data,7)),base=Array.from({length:21},()=>Array(21).fill(null)),reserved=Array.from({length:21},()=>Array(21).fill(false));
function finder(r,c){for(let y=-1;y<=7;y++)for(let x=-1;x<=7;x++){const yy=r+y,xx=c+x;if(yy<0||yy>=21||xx<0||xx>=21)continue;reserved[yy][xx]=true;base[yy][xx]=y>=0&&y<=6&&x>=0&&x<=6&&(y===0||y===6||x===0||x===6||(y>=2&&y<=4&&x>=2&&x<=4))}}
finder(0,0);finder(0,14);finder(14,0);for(let i=8;i<13;i++){base[6][i]=i%2===0;base[i][6]=i%2===0;reserved[6][i]=true;reserved[i][6]=true}base[13][8]=true;reserved[13][8]=true;
const fmt=(mask)=>{const d=8|mask;let v=d<<10;for(let i=14;i>=10;i--)if((v>>>i)&1)v^=0x537<<(i-10);return ((d<<10)|v)^0x5412};const coordsA=[[8,0],[8,1],[8,2],[8,3],[8,4],[8,5],[8,7],[8,8],[7,8],[5,8],[4,8],[3,8],[2,8],[1,8],[0,8]],coordsB=[[8,20],[8,19],[8,18],[8,17],[8,16],[8,15],[8,14],[8,13],[14,8],[15,8],[16,8],[17,8],[18,8],[19,8],[20,8]];coordsA.concat(coordsB).forEach(([r,c])=>{base[r][c]=false;reserved[r][c]=true});
let bit=0,up=true;for(let right=20;right>=1;right-=2){if(right===6)right=5;for(let v=0;v<21;v++){const row=up?20-v:v;for(let j=0;j<2;j++){const col=right-j;if(base[row][col]!==null)continue;base[row][col]=bit<all.length*8?((all[bit>>>3]>>>(7-(bit++&7)))&1)!==0:false}}up=!up}
let best=null,bestScore=Infinity;for(let mask=0;mask<8;mask++){const m=base.map(row=>row.slice());for(let r=0;r<21;r++)for(let c=0;c<21;c++)if(!reserved[r][c]){const masked=[(r+c)%2===0,r%2===0,r%3===0,(r+c)%3===0,(Math.floor(r/2)+Math.floor(c/3))%2===0,(r*c)%2+(r*c)%3===0,((r*c)%2+(r*c)%3)%2===0,((r+c)%2+(r*c)%3)%2===0][mask];if(masked)m[r][c]=!m[r][c]}const f=fmt(mask);coordsA.forEach(([r,c],i)=>m[r][c]=((f>>>i)&1)!==0);coordsB.forEach(([r,c],i)=>m[r][c]=((f>>>i)&1)!==0);let score=0;for(let r=0;r<21;r++){let run=1;for(let c=1;c<21;c++){if(m[r][c]===m[r][c-1])run++;else{if(run>=5)score+=3+run-5;run=1}}if(run>=5)score+=3+run-5}if(score<bestScore){bestScore=score;best=m}}
const scale=8,pad=4,total=(21+pad*2)*scale;let rects='<rect width="100%" height="100%" fill="white"/>';for(let r=0;r<21;r++)for(let c=0;c<21;c++)if(best[r][c])rects+=`<rect x="${(c+pad)*scale}" y="${(r+pad)*scale}" width="${scale}" height="${scale}"/>`;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" shape-rendering="crispEdges"><g fill="#102820">${rects}</g></svg>`}
$('#generate-form').onsubmit=e=>{e.preventDefault();const count=+$('#code-quantity').value;if(!Number.isInteger(count)||count<1||count>300){toast('اختر عددًا من 1 إلى 300');return}const batch=[];for(let i=0;i<count;i++){const n=db.nextCode++;const item={code:`MATH-${String(n).padStart(6,'0')}`,used:false,created:new Date().toISOString()};db.codes.push(item);batch.push(item)}save();renderCodes(batch);toast(`تم إنشاء ${count} كودًا جديدًا`)};
function renderCodes(codes){const cols=+$('#code-columns').value;$('#code-preview').innerHTML=`<div class="print-sheet" style="grid-template-columns:repeat(${cols},1fr)">${codes.map(c=>`<div class="qr-card">${makeQR(c.code)}<span>${c.code}</span></div>`).join('')}</div>`;$('#print-codes').disabled=!codes.length;$('#reprint-codes').disabled=!db.codes.length;$('#preview-caption').textContent=`${codes.length} كود • ${cols} أعمدة • ورقة A4`;$('#code-status').textContent=`${db.codes.length} كود محفوظ حتى الآن. الأكواد المرتبطة بطالب: ${db.students.filter(s=>s.code).length}.`}
$('#code-columns').onchange=()=>{const sheet=$('.print-sheet');if(sheet)sheet.style.gridTemplateColumns=`repeat(${$('#code-columns').value},1fr)`};$('#print-codes').onclick=()=>window.print();
const QR_LIBRARY_URL='https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js';
async function loadQRLibrary(){if(typeof window.jsQR==='function')return;let response;try{response=await caches.open('miyaar-qr-library-v1').then(cache=>cache.match(QR_LIBRARY_URL))}catch{}if(!response){response=await fetch(QR_LIBRARY_URL,{mode:'cors'});if(!response.ok)throw Error('decoder-download');try{const cache=await caches.open('miyaar-qr-library-v1');await cache.put(QR_LIBRARY_URL,response.clone())}catch{}}const source=await response.text(),blob=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));await new Promise((resolve,reject)=>{const script=document.createElement('script');script.onload=()=>{URL.revokeObjectURL(blob);script.remove();resolve()};script.onerror=()=>{URL.revokeObjectURL(blob);script.remove();reject(Error('decoder-load'))};script.src=blob;document.head.appendChild(script)});if(typeof window.jsQR!=='function')throw Error('decoder-global')}
let activeStreams=[];
async function scanStream(video,stream,onCode){const native=typeof window.BarcodeDetector==='function';await loadQRLibrary();const detector=native?new BarcodeDetector({formats:['qr_code']}):null,canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let busy=false,lastScan=0,lastValue='',lastAt=0;const scan=async(now)=>{if(!stream.active)return;if(!busy&&now-lastScan>350){busy=true;lastScan=now;try{let value='';if(detector){try{const codes=await detector.detect(video);value=codes[0]?.rawValue||''}catch{}}if(!value&&video.videoWidth){const fullW=Math.min(video.videoWidth,1600),fullH=Math.round(video.videoHeight*fullW/video.videoWidth);canvas.width=fullW;canvas.height=fullH;ctx.drawImage(video,0,0,fullW,fullH);value=window.jsQR(ctx.getImageData(0,0,fullW,fullH).data,fullW,fullH,{inversionAttempts:'attemptBoth'})?.data||'';if(!value){const sx=Math.round(video.videoWidth*.25),sy=Math.round(video.videoHeight*.15),sw=Math.round(video.videoWidth*.5),sh=Math.round(video.videoHeight*.7),zoomW=1200,zoomH=Math.round(zoomW*sh/sw);canvas.width=zoomW;canvas.height=zoomH;ctx.drawImage(video,sx,sy,sw,sh,0,0,zoomW,zoomH);value=window.jsQR(ctx.getImageData(0,0,zoomW,zoomH).data,zoomW,zoomH,{inversionAttempts:'attemptBoth'})?.data||''}}if(value&&(value!==lastValue||Date.now()-lastAt>2500)){lastValue=value;lastAt=Date.now();if(onCode(value)===true){stream.getTracks().forEach(t=>t.stop());return}}}catch{}finally{busy=false}}requestAnimationFrame(scan)};requestAnimationFrame(scan)}
async function startScan(video,wrap,placeholder,startBtn,stopBtn,onCode){let stream;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play();activeStreams.push(stream);placeholder.style.display='none';wrap.classList.add('scanning');startBtn.hidden=true;stopBtn.hidden=false;await scanStream(video,stream,onCode)}catch{if(stream)stream.getTracks().forEach(t=>t.stop());stopAll();toast(typeof window.BarcodeDetector!=='function'?'لتجهيز المسح أول مرة، اتصل بالإنترنت وحاول مرة أخرى. بعدها يعمل المسح دون إنترنت.':'تعذر تشغيل الكاميرا. تحقق من الإذن وافتح الرابط عبر HTTPS.')}}
function stopAll(){activeStreams.forEach(s=>s.getTracks().forEach(t=>t.stop()));activeStreams=[];$('#video').srcObject=null;$('#scanner-placeholder').style.display='flex';$('#scanner').classList.remove('scanning');$('#camera-btn').hidden=false;$('#stop-camera').hidden=true;$('#link-video').srcObject=null;$('#link-scanner').hidden=true}
$('#camera-btn').onclick=()=>startScan($('#video'),$('#scanner'),$('#scanner-placeholder'),$('#camera-btn'),$('#stop-camera'),recordAttendance);$('#stop-camera').onclick=stopAll;
$('#link-code-btn').onclick=async()=>{const v=$('#link-video'),wrap=$('#link-scanner');wrap.hidden=false;let status=wrap.querySelector('.scan-status');if(!status){status=document.createElement('small');status.className='scan-status';status.style.cssText='display:block;text-align:center;padding:6px;color:#176b39;font-weight:700';wrap.append(status)}status.textContent='وجّه الكود لنصّ المربع وثبّت الموبايل...';let stream,timer;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});v.srcObject=stream;await v.play();activeStreams.push(stream);timer=setTimeout(()=>{status.textContent='لسه ماقراش الكود؛ قرّبه وخليه في نص الصورة، وخلي الصورة واضحة من غير لمعة.'},5000);await scanStream(v,stream,raw=>{if(linkCode(raw)){clearTimeout(timer);status.textContent='اتقري الكود: '+raw;wrap.hidden=true;toast('تم ربط الكود بالطالب.');return true}status.textContent='اتشاف كود لكن مش من أكواد الموقع: '+raw;return false})}catch{clearTimeout(timer);if(stream)stream.getTracks().forEach(t=>t.stop());stopAll();status.textContent='المسح ما اشتغلش. تأكد من الإنترنت أول مرة، واسمح للموقع باستخدام الكاميرا.';toast(typeof window.BarcodeDetector!=='function'?'اتصل بالإنترنت أول مرة ثم حاول تاني.':'تعذر تشغيل الكاميرا. استخدم حقل الكود اليدوي.')}};
$('#student-dialog').addEventListener('close',stopAll);window.addEventListener('pagehide',stopAll);init();
if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>{});
